# Actual TensorFlow Intro

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## Data generation

In [6]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10,10,(observations,1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1,1,(observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)
#Not necesary for the names to be inputs and targets, we can call it whatever

## Solving with TensorFlow

In [7]:
training_data = np.load('TF_intro.npz')

In [12]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
                            tf.keras.layers.Dense(output_size)
                            ])

model.compile(optimizer='sgd',loss='mean_squared_error')

model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=1)

Epoch 1/100
32/32 [==============================] - 0s 611us/step - loss: 33.9583
Epoch 2/100
32/32 [==============================] - 0s 579us/step - loss: 4.2669
Epoch 3/100
32/32 [==============================] - 0s 676us/step - loss: 1.4313
Epoch 4/100
32/32 [==============================] - 0s 676us/step - loss: 0.6364
Epoch 5/100
32/32 [==============================] - 0s 611us/step - loss: 0.4252
Epoch 6/100
32/32 [==============================] - 0s 579us/step - loss: 0.3640
Epoch 7/100
32/32 [==============================] - 0s 611us/step - loss: 0.3415
Epoch 8/100
32/32 [==============================] - 0s 676us/step - loss: 0.3452
Epoch 9/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3395
Epoch 10/100
32/32 [==============================] - 0s 740us/step - loss: 0.3417
Epoch 11/100
32/32 [==============================] - 0s 643us/step - loss: 0.3353
Epoch 12/100
32/32 [==============================] - 0s 643us/step - loss: 0.3451
Epoch 13/100
3

32/32 [==============================] - 0s 579us/step - loss: 0.3444
Epoch 100/100
32/32 [==============================] - 0s 595us/step - loss: 0.3516


## Extract the weigths and bias

In [13]:
model.layers[0].get_weights()

[array([[ 2.041424 ],
        [-2.9718618]], dtype=float32),
 array([4.9885383], dtype=float32)]

In [15]:
weights = model.layers[0].get_weights()[0]
weights

array([[ 2.041424 ],
       [-2.9718618]], dtype=float32)

In [16]:
bias = model.layers[0].get_weights()[1]
bias

array([4.9885383], dtype=float32)

## Extract the outputs (make predictions)

In [17]:
model.predict_on_batch(training_data['inputs'])

array([[ 7.00565434e+00],
       [-3.16277752e+01],
       [-2.37629843e+00],
       [ 1.49958363e+01],
       [-1.83285427e+01],
       [ 4.38832550e+01],
       [-1.35164757e+01],
       [-1.93531399e+01],
       [ 3.12157497e+01],
       [ 1.44704552e+01],
       [-2.57214279e+01],
       [-1.47472401e+01],
       [ 1.27581806e+01],
       [ 1.71956310e+01],
       [ 1.72981548e+01],
       [-8.56078148e+00],
       [ 1.21108341e+01],
       [-2.42677174e+01],
       [-1.08070011e+01],
       [ 5.85808611e+00],
       [ 2.45680485e+01],
       [ 3.36016045e+01],
       [-9.23302460e+00],
       [ 2.58101368e+01],
       [ 1.12452297e+01],
       [ 4.05812531e+01],
       [ 2.02688160e+01],
       [ 1.49938908e+01],
       [ 3.45458269e+00],
       [ 3.50799942e+01],
       [-4.10851555e+01],
       [ 4.68200645e+01],
       [ 3.01648426e+01],
       [-8.47104836e+00],
       [ 8.37671089e+00],
       [-2.30268040e+01],
       [-3.01703968e+01],
       [-1.81684971e+01],
       [-2.6

In [18]:
model.predict_on_batch(training_data['inputs']).roudn(1)

AttributeError: 'numpy.ndarray' object has no attribute 'roudn'